name: assignment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Toast
  bot_toast: ^4.1.3

  #SVG
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_remote_config: ^5.0.3

  #State management
  provider: ^6.1.2

  #Service
  dio: ^5.5.0+1
  intl: ^0.19.0

  #Local data store
  shared_preferences: ^2.2.3

  #Routing
  go_router: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/animation/
