// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByH5jV9YTU5T6Cj2-xbR38CW_S7NdoFXU',
    appId: '1:295261646981:web:56d3603c771b34b7a839ec',
    messagingSenderId: '295261646981',
    projectId: 'assignment-9e39c',
    authDomain: 'assignment-9e39c.firebaseapp.com',
    storageBucket: 'assignment-9e39c.appspot.com',
    measurementId: 'G-494880W3SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhBMi__4KDCN0t8wFaa68PYOTdka036_A',
    appId: '1:295261646981:android:e021ede7f4a9d253a839ec',
    messagingSenderId: '295261646981',
    projectId: 'assignment-9e39c',
    storageBucket: 'assignment-9e39c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5nAdsQK2W-1isnI7mEAXkRLbqLwzEPQ',
    appId: '1:295261646981:ios:e290401a5e948393a839ec',
    messagingSenderId: '295261646981',
    projectId: 'assignment-9e39c',
    storageBucket: 'assignment-9e39c.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5nAdsQK2W-1isnI7mEAXkRLbqLwzEPQ',
    appId: '1:295261646981:ios:e290401a5e948393a839ec',
    messagingSenderId: '295261646981',
    projectId: 'assignment-9e39c',
    storageBucket: 'assignment-9e39c.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByH5jV9YTU5T6Cj2-xbR38CW_S7NdoFXU',
    appId: '1:295261646981:web:81c410ab38a70a7fa839ec',
    messagingSenderId: '295261646981',
    projectId: 'assignment-9e39c',
    authDomain: 'assignment-9e39c.firebaseapp.com',
    storageBucket: 'assignment-9e39c.appspot.com',
    measurementId: 'G-ZB7XHRQTNL',
  );
}
